import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#bdc7db",
        "secondary": "#585f6c",
        "surface-dim": "#d3daea",
        "on-surface": "#151c27",
        "on-secondary-fixed": "#151c27",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed-dim": "#c0c7d6",
        "on-secondary-container": "#5e6572",
        "primary-fixed": "#e5e2e1",
        "surface-variant": "#dce2f3",
        "surface-bright": "#f9f9ff",
        "outline": "#747878",
        "surface-tint": "#5f5e5e",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed": "#1c1b1b",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "surface-container": "#e7eefe",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#121c2a",
        "on-surface-variant": "#444748",
        "tertiary-container": "#121c2a",
        "secondary-container": "#dce2f3",
        "on-primary-container": "#858383",
        "primary-container": "#1c1b1b",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#7a8496",
        "tertiary-fixed": "#d9e3f7",
        "inverse-primary": "#c8c6c5",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",
        "on-error": "#ffffff",
        "background": "#f9f9ff",
        "tertiary": "#000000",
        "outline-variant": "#c4c7c7",
        "on-secondary-fixed-variant": "#404754",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "secondary-fixed": "#dce2f3",
        "on-tertiary-fixed-variant": "#3d4757",
        "on-background": "#151c27"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        icon: ["Material Symbols Outlined"],
        headline: ["var(--font-dm-sans)"],
        body: ["var(--font-dm-sans)"],
        label: ["var(--font-dm-sans)"],
        sans: ["var(--font-dm-sans)", "sans-serif"]
      },
    },
  },
  plugins: [],
};
export default config;
